# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0687e901bfe911b217b01084a32c86ca9a35e253b5a8f2ba8b009699364f6134ad2c0ec4954efd2245d6472210980bc2c97e318c1c31e6efe344e847135c6ae0

test:
  secret_key_base: e9f17d2a39383a547f870d31cc5050f828731bb0e9202c22af7b9b1a4967735747536b5c0f1827dd4508c7e3cd1ffcf410dc5496e3db0f088820e014ce243abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
